# Generated by Django 2.2 on 2020-10-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'akun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'kategori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
                ('harga_per_unit', models.IntegerField(blank=True, null=True)),
                ('stok', models.IntegerField(blank=True, null=True)),
                ('deskripsi', models.CharField(blank=True, max_length=1000, null=True)),
                ('gambar', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'produk',
                'managed': False,
            },
        ),
    ]
