# Generated by Django 2.2 on 2020-10-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akun',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produk',
            options={},
        ),
    ]
